# Reconnect --- config file
# In this file, you can setup some basic settings for the plugin.

# The current version of this configuration. Do NOT change this value!
# If the plugin uses a more recent config version, this config gets replaced by it
# while a backup of the old config will be kept as "config.old.yml".
version: 1

# The text that should be displayed, when the plugin is trying to reconnect a player.
# Leave empty if you don't wish any title or action bar message to be displayed.
reconnecting-text:
  # You can add animated dots to the reconnecting texts by using the {%dots%} variable.

  title: "&7Reconnecting{%dots%}"
  actionbar: "&a&lPlease do not leave! &7Reconnecting to server{%dots%}"

# The text that should be displayed, when the plugin managed to establish a connection to
# the previous server and now connects the player to it.
# Leave empty if you don't wish any title or action bar message to be displayed.
connecting-text:
  title: "&aConnecting..."
  actionbar: "&7Connecting you to the server..."

# The text that should be displayed, when the plugin didn't manage to etablish
# a connection to the previous server and connected the player to the fallback server.
# Leave empty if you don't wish any title or action bar message to be displayed.
failed-text:
  title: "&cReconnecting failed!"
  actionbar: "&eYou have been moved to the fallback server!"


# The maximum amount of reconnect tries the plugin should make, before either connecting the player
# to your fallback-server or disconnecting him. This value cannot be less than 1.
max-reconnect-tries: 20

# The amount of milliseconds the plugin should wait before making a new reconnect try. This value
# cannot be less than zero.
reconnect-time: 1000

# The amount of milliseconds the plugin should wait for a reply from the previous server, until it
# decides to abort that reconnect try. This value cannot be less than 1000.
reconnect-timeout: 5000

# A List containing all servers that don't allow automatic reconnecting.
ignored-servers: [dummy, dummy2]

# This block is necessary for the plugin to differentiate whether a kick happened because of a shutdown or not.
shutdown:
  # When regex is set to false, the kick message must be equal to the following text if the player should be reconnected to that server. (Formatting codes will be ignored though.)
  # When regex is set to true, the regex must match the kick message if the player should be reconnected to that server.
  # Leaving the text empty will lead the plugin to always reconnect the players, no matter what the actual kick-reason was.

  # You can still use the "ServerReconnectEvent" as a plugin developer to decide on your own whether the user should be reconnected automatically
  # or not.

  text: "Server closed"
  regex: false